# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM python:3.10-slim

# Install build dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy project files
COPY pyproject.toml .
COPY src src

# Install Python dependencies
RUN pip install --no-cache-dir hatchling
RUN pip install --no-cache-dir .

# Default command
CMD ["python", "-m", "notion_api_mcp"]
